package com.accenture.exception.response;

import java.io.Serializable;

import org.apache.commons.lang3.builder.ToStringBuilder;
import org.apache.commons.lang3.builder.ToStringStyle;

import lombok.Builder;
import lombok.Getter;
import lombok.Setter;

/**
 * Class to handle the response of the errors generated by the API
 * 
 * @author infrahector@hotmail.com
 */
@Builder
@Getter
@Setter
public class ApiError implements Serializable {

	/**
	 * clave  serial por defecto
	 */
	private static final long serialVersionUID= 1L;
	
	/**
	 * Error
	 */
	private String errorCode;
	
	/**
	 * Tipo error
	 */
	private String errorType;
	
	/**
	 * codigo
	 */
	private String code;
	
	/**
	 * descripcion
	 */
	private String description;
	
	/**
	 * detalle
	 */
	private String detail;
	
	@Override
	public String toString() {
		return ToStringBuilder.reflectionToString(this, ToStringStyle.SHORT_PREFIX_STYLE);
	}
	
}
